# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Shawn Stern
tagline:          'Thoughts on JavaScript, React, Node, and everything in between'
url:              stern-shawn.github.io
baseurl:          /

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:           https://avatars1.githubusercontent.com/u/10067791?v=3&u=842d6de1e395a0a8926d570fc6ca62b022a47994&s=140

author:
  name:           'Shawn Stern'
  url:            https://github.com/stern-shawn

paginate:         5

gems: [jekyll-paginate,jekyll-gist]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stern-shawn

socials:
  email:          stern.shawn@gmail.com
  linkedin:       https://www.linkedin.com/in/shawn-stern-48496747

# Google services
google_analytics: UA-102381336-1
